# Generated by Django 5.0.6 on 2024-06-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default=1, upload_to='post_pictures/'),
            preserve_default=False,
        ),
    ]
